/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package node.http.agent.test;

import org.eclipse.jetty.server.Server;
import org.eclipse.jetty.server.ServerConnector;
import org.eclipse.jetty.server.handler.DebugHandler;

public class App {
    public static void main(String[] args) throws Exception {
        Server server = new Server();

        ServerConnector http = new ServerConnector(server);
        http.setHost("localhost");
        http.setPort(9876);
        http.setIdleTimeout(300000);
        server.addConnector(http);

        DebugHandler debugHandler = new DebugHandler();
        // debugHandler.setOutputStream(System.out);
        debugHandler.setHandler(new HeaderHandler());

        server.setHandler(debugHandler);

        server.start();
        server.join();
    }
}
